### ISSUE TITLE
ppxml2db.py error in handling accountFrom tag

### ISSUE THREAD

**Issue by nmorgens** [pfalcon/ppxml2db#16] opened 2024-10-21 20:06 UTC
I'm currently in the process of trying to reproduce https://github.com/pfalcon/ppxml2db/issues/15 on a sample data set as I've run into the exact same error.

In the process of trying to reproduce I have encountered a different error:

```
Traceback (most recent call last):
  File "/Users/.../ppxml2db.py", line 581, in <module>
    conv.iterparse()
  File "/Users/.../ppxml2db/ppxml2db.py", line 518, in iterparse
    uuid = self.uuid(parent.find("accountFrom"))
  File "/Users/.../ppxml2db.py", line 56, in uuid
    id = el.get("reference")
AttributeError: 'NoneType' object has no attribute 'get'
```

Debug logs:
```
2024-10-21 14:57:36 DEBUG INSERT OR REPLACE INTO latest_price(high, low, volume, value, tstamp, security) VALUES (?, ?, ?, ?, ?, ?) ['-1', '-1', '-1', '21627000000', '2024-10-21', '134b699a-97ef-4572-ab08-adc997b59969']
2024-10-21 14:57:36 DEBUG INSERT OR REPLACE INTO security(uuid, name, tickerSymbol, feed, isRetired, updatedAt, currency) VALUES (?, ?, ?, ?, ?, ?, ?) ['134b699a-97ef-4572-ab08-adc997b59969', 'Coinbase Global, Inc.', 'COIN', 'YAHOO', 0, '2024-10-21T19:03:13.321038Z', 'USD']
2024-10-21 14:57:36 DEBUG INSERT OR REPLACE INTO account(uuid, name, isRetired, updatedAt, currency, _xmlid, type, _order) VALUES (?, ?, ?, ?, ?, ?, ?, ?) ['5e321346-e097-45e4-8891-59c66146b1c3', 'TIRA:Cash', 0, '2024-10-21T18:16:44.619213Z', 'USD', '5', 'account', 7324]
2024-10-21 14:57:36 DEBUG INSERT OR REPLACE INTO xact(uuid, date, amount, shares, updatedAt, type, currency, _xmlid, account, acctype, _order, fees, taxes) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ['13fa3254-679e-4039-a21f-623171a84061', '2023-01-01T00:00', '1000000', '0', '2024-10-21T18:17:22.392168Z', 'DEPOSIT', 'USD', '7', 'd7b677f6-bd03-4ede-85a3-4afab72def4c', 'account', 7350, 0, 0]
2024-10-21 14:57:36 DEBUG INSERT OR REPLACE INTO xact(uuid, date, amount, shares, updatedAt, type, currency, _xmlid, account, acctype, _order, security, fees, taxes) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ['81964c61-b4f8-4c6b-acef-6b58202ef3f3', '2024-01-01T00:00', '1000000', '16257000000', '2024-10-21T18:18:25.850005Z', 'BUY', 'USD', '11', 'ac284565-8f6f-43c0-904e-b42329f7eaee', 'portfolio', 0, 'a0d5e06e-fecc-4d44-87e8-272b3fe03440', 32, 0]
2024-10-21 14:57:36 DEBUG INSERT OR REPLACE INTO xact_unit(xact, type, amount, currency) VALUES (?, ?, ?, ?) ['81964c61-b4f8-4c6b-acef-6b58202ef3f3', 'FEE', '32', 'USD']
2024-10-21 14:57:36 DEBUG UPDATE account SET _order=? WHERE _xmlid=? (7412, '10')
2024-10-21 14:57:36 DEBUG Processing transactionFrom element: b'<transactionFrom reference="12"/>\n                    '
2024-10-21 14:57:36 DEBUG INSERT OR REPLACE INTO xact(uuid, date, amount, shares, updatedAt, type, currency, _xmlid, account, acctype, _order, security, fees, taxes) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ['ea9e34c4-e289-44cd-8020-57f2e2a91d0b', '2024-02-01T00:00', '1024630', '16257000000', '2024-10-21T18:19:17.026475Z', 'TRANSFER_IN', 'USD', '15', 'c3b35945-139f-4052-95f9-fa24633d4a56', 'portfolio', 0, 'a0d5e06e-fecc-4d44-87e8-272b3fe03440', 0, 0]
2024-10-21 14:57:36 DEBUG UPDATE account SET _order=? WHERE _xmlid=? (7458, '10')
2024-10-21 14:57:36 DEBUG Processing transactionFrom element: b'<transactionFrom id="18">\n                              <uuid>260f7503-21cf-4b25-9962-54af27fced8a</uuid>\n                              <date>2024-01-25T00:00</date>\n                              <currencyCode>USD</currencyCode>\n                              <amount>302525</amount>\n                              <security reference="4"/>\n                              <crossEntry class="portfolio-transfer" reference="17"/>\n                              <shares>2500000000</shares>\n                              <updatedAt>2024-10-21T19:06:34.063363Z</updatedAt>\n                              <type>TRANSFER_OUT</type>\n                            </transactionFrom>\n                            '
Traceback (most recent call last):
  File "/Users/.../ppxml2db/ppxml2db.py", line 581, in <module>
    conv.iterparse()
  File "/Users/.../ppxml2db/ppxml2db.py", line 518, in iterparse
    uuid = self.uuid(parent.find("accountFrom"))
  File "/Users/.../ppxml2db.py", line 56, in uuid
    id = el.get("reference")
AttributeError: 'NoneType' object has no attribute 'get'
```

Working dataset:
[2024-10-21_Portfolio-Transaction-Error.zip](https://github.com/user-attachments/files/17466343/2024-10-21_Portfolio-Transaction-Error.zip)

I'm happy to try and help work out these issues but am not very familiar with the structure of the pp xml file.

**Comment by pfalcon** [comment] 2024-10-23 06:01
Thanks for providing the test data. In this case, the issue is transactions of TRANSFER_OUT type, which apparently weren't tried by anyone before and need adhoc handling. I'll look into that as time permits.

P.S. I assume the data provided is a repro testcase and doesn't contain any private information. Otherwise, please remove it or let me know and I'll remove it.

**Comment by Rich28** [comment] 2024-10-23 12:33
> Thanks for providing the test data. In this case, the issue is transactions of TRANSFER_OUT type, which apparently weren't tried by anyone before and need adhoc handling. I'll look into that as time permits.
> 
That's interesting.  In my case there aren't any transfer out transactions, but there are some inbound as well as outbound deliveries 
- could this be the cause of the issue I've reported??

**Comment by nmorgens** [comment] 2024-10-28 16:46
@pfalcon There is no private info, thanks for confirming. 

@Rich28 It's hard to say, that doesn't seem to be the case in my scenario as I don't have any inbound/outbound deliveries. I am hitting the same error message on line 505 though. I'll keep playing around and see if I can recreate it from a fresh data set.

**Comment by pfalcon** [comment] 2024-12-22 04:48
@nmorgens : Thanks again for providing a testcase. I finally found time to look into it, and for your sample file, the issue is fixed in the latest version 1.5 in the repo. Can you please confirm that it works for your full file?

**Comment by pfalcon** [comment] 2024-12-30 06:55
Assuming fixed, closing. Feel free to comment to reopen.

**Closed by pfalcon** 2024-12-30 06:55 UTC

**Comment by flywire** [comment] 2025-01-26 04:01
> In this case, the issue is transactions of TRANSFER_OUT type, which apparently weren't tried by anyone before and need adhoc handling

More likely it has been a problem of communicating issues in files containing confidential data.
